[ADD] mail_activity_automation: create module
ingadhoc/miscellaneous pull request #126
Opened 2023-08-04 18:49 UTC by lav-adhoc

2023-08-04 18:50 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/126).

2023-08-07 20:34 UTC, nicomacr requested changes

2023-08-07 20:34 UTC, nicomacr commented on mail_activity_automation/README.rst
> +* Complete
```suggestion
*This module incorporates the functionality of automatically executing the activity, whether it is sending an email or marking Done.
```

2023-08-07 20:34 UTC, nicomacr commented on mail_activity_automation/README.rst
> +#. Just use it.
```suggestion
#.  Scheduler an activity using the activity type with "Run automatically" on.
```

2023-08-07 20:34 UTC, nicomacr commented on mail_activity_automation/README.rst
> +#. Don't need any configuration
```suggestion
#. In the activities type configure with "run automatically".

```

2023-08-11 00:52 UTC, jjscarafia requested changes

2023-08-11 00:52 UTC, jjscarafia commented on mail_activity_automation/models/mail_activity.py
> +        return super()._action_done(feedback, attachment_ids)
tal vez no rompa nada, pero entiendo que los argumentos  opcionales al llamar a super hay que pasarlos así:
`        return super()._action_done(feedback=feedback, attachment_ids=attachment_ids)
`

2023-08-11 00:52 UTC, jjscarafia commented on mail_activity_automation/models/mail_activity_type.py
> +    run_automatically = fields.Boolean(help="Si marca esta opción, llegada la fecha de vencimiento, se enviará la plantilla seleccionada y se marcará la actividad como realizado.")
a este campo lo haría computado, almacenado, readonly= False.
Cosa de que si alguien agregua un template se resetee a "false" porque si no el campo deja de estar visible pero va a seguir marcado como True.

Ahora que pienso tal vez simplificaría y lo dejaría siempre disponible y ajustaría el help (y funcionalidada a esta lógica)
"Si marca esta opción, llegada la fecha de vencimiento, se marcará la actividad como realizada. Si hay plantillas de email definidas se enviaran las mismas."

Luego el campo computado mail_template_ids_count puede desaparecer y acá tenemos que recorrer las plantillas https://github.com/ingadhoc/miscellaneous/pull/126/files#diff-d6416e453531d11717342083d0e56c5cedb79883a8e4e73585446b7634eeee3bR14-R15

Como les parezca, solo ideas..

2023-08-15 19:55 UTC, nicomacr commented
@roboadhoc r+

2023-08-15 20:58 UTC, closed without merging