[MIG] okr_management: Migration to 17.0
ingadhoc/miscellaneous pull request #165
Opened 2024-02-01 13:35 UTC by mem-adhoc

Task: 34208

2024-02-01 13:36 UTC, roboadhoc commented
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/miscellaneous/pull/165).

2024-02-07 18:12 UTC, augusto-weiss requested changes

2024-02-07 18:12 UTC, augusto-weiss commented on okr_management/models/okr_key_result.py
> +    _name = 'okr.key.result'
usar "." cuando es un submodelo, "_" cuando es parte del nombre (por ej "key_result")

2024-02-07 18:12 UTC, augusto-weiss commented on okr_management/models/okr_key_result.py
> +    objective =fields.Text()
El objective, deberia ser un objective_id relacionado al modelo okr.objective

2024-02-07 18:12 UTC, augusto-weiss commented on okr_management/models/okr_management.py
> +    _name = 'okr.management'
Esto tendira que ser el modelo okr.objective

2024-02-07 18:12 UTC, augusto-weiss commented on okr_management/models/okr_key_result.py
> +    )
Aca son necesarios 3 campos:
Target que es el puntaje a obtener (esta mas abajo, eso esta bien)
Resultado (es el resultado parcial, este falta)
Progress esta bien y es computado pero creo que lo estas usando como el campo anterior (Resultado)

2024-02-07 18:12 UTC, augusto-weiss commented on okr_management/models/okr_key_result.py
> +    @api.depends('peso', 'target')
Faltan dependencias a resultado (campo que no existe)

La dependdencia a peso esta bien pero el campo no existe

2024-02-07 18:12 UTC, augusto-weiss commented on okr_management/models/okr_key_result.py
> +                prog = rec.importance
Revisar formula del excel para implementar aca

2024-02-07 18:12 UTC, augusto-weiss commented on okr_management/models/okr_management.py
> +    result = fields.Float()
Result deberia ser computado y tener en cuenta el progreso que tienen los key result

2024-02-07 18:12 UTC, augusto-weiss commented on okr_management/__manifest__.py
> +    'depends': [
Agregar dependencia minimo a modulo 'base'

2024-02-07 18:12 UTC, augusto-weiss commented on okr_management/__manifest__.py
> +    'application': False,
'application': True

2025-10-16 19:09 UTC, closed without merging